import type { Metadata } from 'next'
import BaseLayout from '@/layout/base'
import './globalStyle.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="zh-CN">
      <body>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  )
}

export default RootLayout
